Add annotations
Icinga/icinga-kubernetes-web pull request #42
Opened 2024-05-21 11:46 UTC by jhoxhaa

2024-06-02 08:59 UTC, lippserd commented on library/Kubernetes/Web/Annotations.php
> +            $this->addHtml(new HorizontalKeyValue($annotation->name, $annotation->value)); //?
Why the `//?`?

2024-06-02 09:00 UTC, lippserd requested changes

2024-06-02 09:00 UTC, lippserd commented on library/Kubernetes/Web/Annotations.php
> +    protected $tag = 'section';
Move `$tag` before `$annotations`.

2024-06-02 10:50 UTC, jhoxhaa commented on library/Kubernetes/Web/Annotations.php
> +            $this->addHtml(new HorizontalKeyValue($annotation->name, $annotation->value)); //?
Forgot to delete.

2024-06-03 14:03 UTC, lippserd approved these changes

2024-06-03 14:03 UTC, merged